# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado_project18.3/Color_Snake/Color_Snake.cache/wt [current_project]
set_property parent.project_path D:/Vivado_project18.3/Color_Snake/Color_Snake.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/23154/Desktop/SEA-Tutorial/FPGA_IP [current_project]
update_ip_catalog
set_property ip_output_repo d:/Vivado_project18.3/Color_Snake/Color_Snake.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/50_r.coe
add_files D:/50_g.coe
add_files D:/50_b.coe
add_files D:/20_r.coe
add_files D:/20_g.coe
add_files D:/20_b.coe
add_files D:/body_r.coe
add_files D:/body_g.coe
add_files D:/body_b.coe
read_verilog -library xil_defaultlib {
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/Change_ground.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/Driver_HDMI.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/Snake_position.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/Video_Generator.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/clk_div.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/create_apple.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/die_judge.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/eat_apple.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/key_direct.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/key_pro.v
  D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/new/snake_top.v
}
read_ip -quiet D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/G_ROM_1/G_ROM.xci
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/G_ROM_1/G_ROM_ooc.xdc]

read_ip -quiet D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/B_ROM_1/B_ROM.xci
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/B_ROM_1/B_ROM_ooc.xdc]

read_ip -quiet D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/R_ROM_1/R_ROM.xci
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/R_ROM_1/R_ROM_ooc.xdc]

read_ip -quiet D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/BODY_R_ROM/BODY_R_ROM.xci
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/BODY_R_ROM/BODY_R_ROM_ooc.xdc]

read_ip -quiet D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/BODY_G_ROM/BODY_G_ROM.xci
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/BODY_G_ROM/BODY_G_ROM_ooc.xdc]

read_ip -quiet D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/BODY_B_ROM/BODY_B_ROM.xci
set_property used_in_implementation false [get_files -all d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/BODY_B_ROM/BODY_B_ROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files D:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/constrs_1/new/system.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top snake_top -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef snake_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file snake_top_utilization_synth.rpt -pb snake_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
