# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/B_ROM_1/B_ROM.xci
# IP: The module: 'B_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/B_ROM_1/B_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/B_ROM_1/B_ROM.xci
# IP: The module: 'B_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_project18.3/Color_Snake/Color_Snake.srcs/sources_1/ip/B_ROM_1/B_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
